# See the documentation for all configuration options https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      # This repository does not run in a context that is accessible by users or external requests. Run Dependabot once a month to reduce the frequency of PRs.
      interval: 'monthly'
    commit-message:
      prefix: "chore(deps): "
    
    # The version of AWS CDK libraries must match those from @guardian/cdk.
    # We'd never be able to update them here independently, so just ignore them.
    ignore:
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"
      - dependency-name: "constructs"

    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      code-quality:
        patterns:
          - "@guardian/eslint-config-typescript"
          - "@guardian/prettier"
          - "eslint"
          - "eslint-plugin-prettier"
